#!/usr/bin/env bash
# scripts/install_hooks.sh
#
# Installs a pre-push git hook that runs the producer evolution gate on every
# changed contract YAML before a push reaches the remote.
#
# Usage
#   bash scripts/install_hooks.sh
#
# After installation, every `git push` will:
#   1. Find contract YAMLs changed between the local branch and the remote.
#   2. Run `python -m contracts.evolution_gate` for each changed YAML.
#   3. Block the push (exit 1) if any contract has breaking field removals.
#
# To bypass in an emergency (use sparingly):
#   git push --no-verify

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-push"

cat > "$HOOK_FILE" << 'HOOK'
#!/usr/bin/env bash
# .git/hooks/pre-push  — generated by scripts/install_hooks.sh
#
# Called by `git push` before packets are transmitted.
# Stdin: "<local-ref> <local-sha1> <remote-ref> <remote-sha1>" per line.
# Exit non-zero to abort the push.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
CONTRACT_DIR="generated_contracts"
PYTHON="${VIRTUAL_ENV:+$VIRTUAL_ENV/bin/python}"
PYTHON="${PYTHON:-python}"

gate_failures=0

while IFS=' ' read -r local_ref local_sha remote_ref remote_sha; do
    # Deleted branches have the null SHA; nothing to check.
    null_sha="0000000000000000000000000000000000000000"
    if [[ "$local_sha" == "$null_sha" ]]; then
        continue
    fi

    # Determine the base to diff against.
    if [[ "$remote_sha" == "$null_sha" ]]; then
        # New remote branch — diff against the common ancestor with main, or
        # just check the working tree against HEAD if no history exists.
        base_ref="HEAD"
    else
        base_ref="$remote_sha"
    fi

    # Find contract YAMLs that differ between base and the commit being pushed.
    mapfile -t changed_contracts < <(
        git diff --name-only "$base_ref" "$local_sha" -- "$CONTRACT_DIR/*.yaml" \
            "$CONTRACT_DIR/**/*.yaml" 2>/dev/null || true
    )

    if [[ ${#changed_contracts[@]} -eq 0 ]]; then
        continue
    fi

    echo "Evolution gate: checking ${#changed_contracts[@]} changed contract(s)..."

    for contract_path in "${changed_contracts[@]}"; do
        "$PYTHON" -m contracts.evolution_gate \
            --contract "$REPO_ROOT/$contract_path" \
            --proposed-ref "$local_sha" \
            --current-ref "$base_ref" \
            2>&1 || gate_failures=$((gate_failures + 1))
    done
done

if [[ $gate_failures -gt 0 ]]; then
    echo ""
    echo "Push blocked: $gate_failures contract(s) failed the evolution gate."
    echo "Fix the breaking changes or update the registry before pushing."
    echo "To bypass (emergency only): git push --no-verify"
    exit 1
fi

exit 0
HOOK

chmod +x "$HOOK_FILE"
echo "Installed pre-push hook at $HOOK_FILE"
echo "Every push will now run the producer evolution gate on changed contracts."
