"""Migrate Week 2 audit reports into the Week 7 canonical JSONL shape.

This script converts a markdown audit report generated by the Automaton Auditor
into a single JSONL record per report. The output schema mirrors the friend-style
verdict object:

    {
      "verdict_id": "...",
      "target_ref": "...",
      "rubric_id": "...",
      "rubric_version": "1.0.0",
      "scores": {
        "criterion_id": {
          "score": 3,
          "evidence": [...],
          "notes": "..."
        }
      },
      "overall_verdict": "PASS",
      "overall_score": 3.75,
      "confidence": 0.92,
      "evaluated_at": "2026-04-01T19:46:06.376133Z"
    }

The parser is intentionally conservative:
- it only uses information present in the report when available
- it supports both "Dimension" and "Criterion" headings
- it tolerates reports that omit confidence or rubric metadata by deriving
  stable fallbacks
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


SECTION_HEADING_PATTERN = re.compile(
    r"^\s*###\s+(?:Dimension|Criterion)\s*:\s*([a-z0-9_\-]+)\s*$",
    flags=re.IGNORECASE | re.MULTILINE,
)
FINAL_SCORE_PATTERN = re.compile(
    r"\*\*Final Score:\*\*\s*(\d+(?:\.\d+)?)/5",
    flags=re.IGNORECASE,
)
OVERALL_SCORE_PATTERN = re.compile(
    r"\*\*Overall Score:\*\*\s*([0-9]+(?:\.[0-9]+)?|N/A)",
    flags=re.IGNORECASE,
)
OVERALL_VERDICT_PATTERN = re.compile(
    r"\*\*(?:Overall Verdict|Audit Status|Verdict):\*\*\s*([A-Z_]+)",
    flags=re.IGNORECASE,
)
TARGET_REF_PATTERN = re.compile(
    r"\*\*(?:Repository|Target|Repository URL|Target Ref):\*\*\s*(.+)$",
    flags=re.IGNORECASE | re.MULTILINE,
)
CONFIDENCE_PATTERN = re.compile(
    r"\*\*Confidence:\*\*\s*([0-9]+(?:\.[0-9]+)?)",
    flags=re.IGNORECASE,
)
EVALUATED_AT_PATTERN = re.compile(
    r"\*\*(?:Evaluated At|Evaluated at|Generated At|Generated at):\*\*\s*(.+)$",
    flags=re.IGNORECASE | re.MULTILINE,
)
CITED_EVIDENCE_PATTERN = re.compile(
    r"^\s*-\s*Cited Evidence:\s*(.+?)\s*$",
    flags=re.IGNORECASE | re.MULTILINE,
)
CITED_PATTERN = re.compile(
    r"^\s*-\s*Cited:\s*(.+?)\s*$",
    flags=re.IGNORECASE | re.MULTILINE,
)
FILE_LEVEL_PATTERN = re.compile(
    r"^\s*\*\*File-level Remediation Targets:\*\*\s*(.+?)\s*$",
    flags=re.IGNORECASE | re.MULTILINE,
)
DISSENT_PATTERN = re.compile(
    r"\*\*Dissent Summary:\*\*\s*(.+?)(?:\n\s*\n|\n###\s+|\Z)",
    flags=re.IGNORECASE | re.DOTALL,
)
DETERMINISTIC_PATTERN = re.compile(
    r"\*\*Deterministic Resolution:\*\*\s*(.+?)(?:\n\s*\n|\n###\s+|\Z)",
    flags=re.IGNORECASE | re.DOTALL,
)

DEFAULT_REPORT_FOLDERS = (
    "audit/report_onpeer_generated",
    "audit/report_on_peer_generated",
    "audit/report_bypeer_received",
    "audit/report_onself_generated",
)


@dataclass(frozen=True)
class Section:
    criterion_id: str
    body: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Migrate Week 2 audit report markdown into canonical JSONL."
    )
    parser.add_argument(
        "--report",
        default="",
        help=(
            "Path to a markdown report file or a directory containing reports. "
            "If omitted, the script searches the standard audit folders."
        ),
    )
    parser.add_argument(
        "--rubric",
        default="",
        help="Optional path to rubric JSON used to derive rubric_id and version.",
    )
    parser.add_argument(
        "--output",
        default="outputs/week2/verdicts.jsonl",
        help="Destination JSONL file.",
    )
    return parser.parse_args()


def normalize_whitespace(text: str | None) -> str:
    if not text:
        return ""
    return re.sub(r"\s+", " ", text).strip()


def stable_uuid(*parts: str) -> str:
    seed = "::".join(parts)
    return str(uuid.uuid5(uuid.NAMESPACE_URL, seed))


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def load_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(load_text(path))


def find_report_files(report_arg: str | None) -> list[Path]:
    if report_arg:
        path = Path(report_arg)
        if path.is_file():
            return [path]
        if path.is_dir():
            return sorted(path.glob("*.md"))
        alt = Path(report_arg.replace("report_on_peer_generated", "report_onpeer_generated"))
        if alt.is_dir():
            return sorted(alt.glob("*.md"))
        if alt.is_file():
            return [alt]
        raise FileNotFoundError(f"Report path not found: {report_arg}")

    for folder in DEFAULT_REPORT_FOLDERS:
        path = Path(folder)
        if path.is_dir():
            reports = sorted(path.glob("*.md"))
            if reports:
                return reports
    return []


def split_sections(report_text: str) -> list[Section]:
    matches = list(SECTION_HEADING_PATTERN.finditer(report_text))
    sections: list[Section] = []
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(report_text)
        sections.append(Section(criterion_id=match.group(1).strip(), body=report_text[start:end]))
    return sections


def extract_lines(pattern: re.Pattern[str], text: str) -> list[str]:
    values: list[str] = []
    for match in pattern.finditer(text):
        raw = normalize_whitespace(match.group(1))
        if not raw:
            continue
        parts = [normalize_whitespace(part) for part in re.split(r"\s*[,;]\s*", raw)]
        values.extend([part for part in parts if part])
    return values


def parse_score(section_body: str) -> float | None:
    match = FINAL_SCORE_PATTERN.search(section_body)
    if not match:
        return None
    try:
        return float(match.group(1))
    except ValueError:
        return None


def parse_section_notes(section_body: str) -> str:
    for pattern in (DISSENT_PATTERN, DETERMINISTIC_PATTERN):
        match = pattern.search(section_body)
        if match:
            return normalize_whitespace(match.group(1))
    return ""


def parse_section_evidence(section_body: str) -> list[str]:
    evidence: list[str] = []
    evidence.extend(extract_lines(CITED_EVIDENCE_PATTERN, section_body))
    evidence.extend(extract_lines(CITED_PATTERN, section_body))
    evidence.extend(extract_lines(FILE_LEVEL_PATTERN, section_body))
    deduped: list[str] = []
    seen: set[str] = set()
    for item in evidence:
        if item not in seen:
            seen.add(item)
            deduped.append(item)
    return deduped


def parse_overall_score(report_text: str, criterion_scores: list[float]) -> float:
    match = OVERALL_SCORE_PATTERN.search(report_text)
    if match:
        raw = match.group(1)
        if raw.upper() != "N/A":
            try:
                return float(raw)
            except ValueError:
                pass
    if criterion_scores:
        return round(sum(criterion_scores) / len(criterion_scores), 2)
    return 0.0


def parse_overall_verdict(report_text: str, overall_score: float) -> str:
    match = OVERALL_VERDICT_PATTERN.search(report_text)
    if match:
        return match.group(1).upper()
    if overall_score >= 3.5:
        return "PASS"
    if overall_score >= 2.5:
        return "CONDITIONAL"
    return "BLOCK"


def parse_target_ref(report_text: str, report_path: Path) -> str:
    match = TARGET_REF_PATTERN.search(report_text)
    if match:
        return normalize_whitespace(match.group(1))
    return report_path.stem


def parse_confidence(report_text: str, overall_score: float, criterion_scores: list[float]) -> float:
    match = CONFIDENCE_PATTERN.search(report_text)
    if match:
        try:
            value = float(match.group(1))
            return max(0.0, min(1.0, value))
        except ValueError:
            pass

    if not criterion_scores:
        return 0.5

    spread = max(criterion_scores) - min(criterion_scores)
    raw = 0.70 + (overall_score * 0.06) - (spread * 0.01)
    return round(max(0.5, min(0.99, raw)), 2)


def parse_evaluated_at(report_text: str) -> str:
    match = EVALUATED_AT_PATTERN.search(report_text)
    if match:
        raw = normalize_whitespace(match.group(1))
        if raw:
            return raw
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def load_rubric_metadata(rubric_arg: str | None, report_text: str) -> tuple[str, str]:
    if rubric_arg:
        rubric_path = Path(rubric_arg)
        if rubric_path.is_file():
            rubric = load_json(rubric_path)
            metadata = rubric.get("rubric_metadata") or {}
            version = normalize_whitespace(str(metadata.get("version") or "1.0.0")) or "1.0.0"
            rubric_id = metadata.get("rubric_id")
            if rubric_id:
                return str(rubric_id), version
            return sha256_text(json.dumps(rubric, sort_keys=True, ensure_ascii=False)), version

    sections = split_sections(report_text)
    rubric_key = "\n".join(section.criterion_id for section in sections) or report_text
    return sha256_text(rubric_key), "1.0.0"


def build_scores(report_text: str) -> tuple[dict[str, dict[str, Any]], list[float]]:
    sections = split_sections(report_text)
    scores: dict[str, dict[str, Any]] = {}
    numeric_scores: list[float] = []

    for section in sections:
        score = parse_score(section.body)
        if score is None:
            continue

        numeric_scores.append(score)
        evidence = parse_section_evidence(section.body)
        notes = parse_section_notes(section.body)
        if not notes:
            notes = f"Parsed from markdown section {section.criterion_id}"
        if not evidence:
            evidence = [f"Parsed section {section.criterion_id} from report markdown"]

        scores[section.criterion_id] = {
            "score": score,
            "evidence": evidence,
            "notes": notes,
        }

    return scores, numeric_scores


def build_record(report_path: Path, rubric_arg: str | None = None) -> dict[str, Any]:
    report_text = load_text(report_path)
    scores, numeric_scores = build_scores(report_text)
    target_ref = parse_target_ref(report_text, report_path)
    rubric_id, rubric_version = load_rubric_metadata(rubric_arg, report_text)
    overall_score = parse_overall_score(report_text, numeric_scores)
    overall_verdict = parse_overall_verdict(report_text, overall_score)
    confidence = parse_confidence(report_text, overall_score, numeric_scores)
    evaluated_at = parse_evaluated_at(report_text)

    verdict_id = stable_uuid(target_ref, rubric_id, rubric_version, report_path.as_posix())
    return {
        "verdict_id": verdict_id,
        "target_ref": target_ref,
        "rubric_id": rubric_id,
        "rubric_version": rubric_version,
        "scores": scores,
        "overall_verdict": overall_verdict,
        "overall_score": round(overall_score, 2),
        "confidence": confidence,
        "evaluated_at": evaluated_at,
    }


def write_jsonl(records: Iterable[dict[str, Any]], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="\n") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")


def main() -> int:
    args = parse_args()
    try:
        report_paths = find_report_files(args.report)
        if not report_paths:
            print(
                "No Week 2 markdown reports found. Pass --report to a report file or "
                "create audit/report_onpeer_generated/*.md first.",
                file=sys.stderr,
            )
            return 1

        records = [build_record(report_path, args.rubric or None) for report_path in report_paths]
        write_jsonl(records, Path(args.output))
        print(f"Wrote {len(records)} record(s) to {args.output}")
        return 0
    except Exception as exc:  # noqa: BLE001
        print(f"Migration failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
